services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: alibou
      POSTGRES_PASSWORD: alibou
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    # Initial database setup
    command: >
      bash -c "
        echo \"PostgreSQL starting...\"
        /usr/local/bin/docker-entrypoint.sh postgres &
        sleep 10
        echo \"Creating databases...\"
        psql -U alibou -c \"CREATE DATABASE students;\"
        psql -U alibou -c \"CREATE DATABASE schools;\"
        psql -U alibou -c \"CREATE DATABASE attendance;\"
        psql -U alibou -c \"CREATE DATABASE facial_recognition;\"
        echo \"Databases created!\"
        wait
      "

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgresql

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

networks:
  postgres:
    driver: bridge
  zipkin:
    driver: bridge

volumes:
  postgres:
  pgadmin: