eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8060
spring:
  application:
    name: attendance
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/attendance
    username: postgres
    password: shehan17
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    students-url: http://localhost:8222/api/v1/students
    facial-recognition-url: http://localhost:8222/api/v1/facial-recognition

management:
  tracing:
    sampling:
      probability: 1.0